# Generated by Django 5.0.4 on 2024-05-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddepositaccount',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='recurringdepositaccount',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='recurringdepositaccount',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='fixeddepositaccount',
            name='months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixeddepositaccount',
            name='years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringdepositaccount',
            name='months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringdepositaccount',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
