# Generated by Django 5.0.4 on 2024-05-06 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddepositaccount',
            name='source_account_id',
        ),
        migrations.RemoveField(
            model_name='recurringdepositaccount',
            name='source_account_id',
        ),
        migrations.AddField(
            model_name='fixeddepositaccount',
            name='source_account',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposit_source_accounts', to='banking.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringdepositaccount',
            name='source_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_deposit_source_accounts', to='banking.account'),
            preserve_default=False,
        ),
    ]
