# Generated by Django 5.0.4 on 2024-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_limit',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
