# Generated by Django 5.0.4 on 2024-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_fixeddepositaccount_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
