# Generated by Django 5.0.4 on 2024-04-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_recurringdepositaccount_intial_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringdepositaccount',
            old_name='monthly_deposit_amount',
            new_name='deposit_amounts',
        ),
    ]
