# Generated by Django 5.0.4 on 2024-05-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_account_transaction_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='transactions_made',
        ),
    ]
