# Generated by Django 5.0.4 on 2024-05-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_remove_account_transactions_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='transaction_limit',
        ),
    ]
