# Generated by Django 5.0.4 on 2024-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_rename_deposit_amounts_recurringdepositaccount_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
