# Generated by Django 5.0.4 on 2024-05-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
